/** @jsx jsx */
import { jsx } from '@emotion/core';

import PropertyListItem from './PropertyListItem';

import withPropertyData from '../helpers/withPropertyData';
import {
  getFormattedCurrency,
  getGrossYield
} from '../helpers/utils';

import {
  propertiesTableStyle,
  propertiesListTableHeadingStyle,
  propertyTableRow,
  informationIconStyle,
} from '../styles/PropertiesList.css';

import { srOnly } from '../styles/utils.css';

const PropertiesList = ({ properties }) => {
  return (
    <table css={propertiesTableStyle}>
      <caption css={srOnly}>Information for current {properties.length} properties</caption>

      <thead>
        <tr css={propertyTableRow}>
          <th scope="col" css={propertiesListTableHeadingStyle}>
            <span css={srOnly}>Image</span>
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            Address
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            Price
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            Current<br />Rent
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            Gross<br />Yield
            {' '}
            <span title="Gross yield is the annual income generated by an asset before any expenses, divided by its purchase price.
    Monthly rent x 12 months, divided by purchase price.">
              <span aria-hidden="true" css={informationIconStyle}>&#xf129;</span>
            </span>
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            Year<br />Built
          </th>

          <th scope="col" css={propertiesListTableHeadingStyle}>
            <span css={srOnly}>See details</span>
          </th>
        </tr>
      </thead>

      <tbody>
      {properties.map(property => {
        return withPropertyData(PropertyListItem, {
          key: property.id,
          propertyDetailUrl: `${process.env.PUBLIC_URL}/properties/${property.id}`,
          formattedListPrice: getFormattedCurrency(property.financial.listPrice),
          formattedMonthlyRent: getFormattedCurrency(property.financial.monthlyRent),
          grossYield: getGrossYield(property.financial.monthlyRent, property.financial.listPrice),
          ...property
        });
      })}
      </tbody>
    </table>
  );
};

export default PropertiesList;
